language: r
cache: packages
r: 
- release
- devel
sudo: true
warnings_are_errors: true

addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_install:
- tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator
  needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize

r_packages:
- covr
- drat

after_success:
- Rscript -e 'devtools::test()'
- Rscript -e 'covr::codecov()'
- Rscript -e 'remove.packages("stringi")'
- Rscript -e 'install.packages("stringi")'
- test $TRAVIS_R_VERSION_STRING != "release" && Rscript -e 'aspell(files = "tests/testthat/Engaging-students/Report.tex", filter = "Sweave", control = c("-t", "--master=en_AU"))'
- test $TRAVIS_R_VERSION_STRING == "release" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  secure: pD2ZiEBmI75wsJ9IiN60ZswMmoWlmLakclPyc3gOHkV5tOSIyOcSm5bXcegji5wNppF29UhPmV1oVI0WhZWC+Qg2WLioygwgp9p1D5mUzYTlsPISV0IdjBuzqyJu4SkF+yO71QsKdd1Xuh/3+ZJZGNKos/F3NAtw0ClQKfv+MI8bo1zno/mC3Ri1UZsbSQeMAQ4LeKYSghKgTvP2AyqnlsxaUDHHLTvh3Svjbd0APmJQ/HnB5C/U76Y1uSdsE9F60JTUH8A9oyuBP/vU3jZgZldzoU+uMqGu1WqOFqV35fMsc7pAjNMqkF5HKNHO00fk9aq3JgwOJOz50vRqairLvxYSGx89OtQ1CMrjf9/7HDe92wRhZYHaaCSN7onQVR8BGiRqkqSs/fM40XJrNFzif5VuImBi08qrBouB+qzgu9ILUma/RNlBuYcaIdtHDCa4aUP9GWnS4tg6R/xz9JXM+b3q5L0GVap5Yu7OXrniT5ZOydA5bukqdZ7gDeEGGhcD+CO/ximZTDOJgsN4nNhfEgaFRLljxS9ZtDQV2UOAxp1nK/HXKncQbqSq5DF0QbYIyoh5nUzPDdp2+60KVD7mC8y0rGzSHo58yiN9PAH91SJ+vyVqQ+8kcQoqMFQOAvhVnqJCN4w+CPyiKD0/b9HclqyAX9Cu0z4DZ2KscLvHCKI=
