language: r
cache: packages
warnings_are_errors: true
sudo: true

before_install:
  - sudo apt-get intall dictionaries-common
  - sudo apt-get install hunspell-en-au

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
