language: r
cache: packages
warnings_are_errors: true
before_install:
- tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator
  needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
addons:
  apt:
    packages:
    - libhunspell-dev
r_packages:
- covr
- drat
- devtools
- roxygen2
- hunspell
after_success:
- Rscript -e 'devtools::test()'
- Rscript -e 'covr::codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && 
    test $TRAVIS_BRANCH == "master" && 
    bash deploy.sh
env:
  global:
    secure: VIqdU9J8GeIm1kg/CAAiQORwK3yweDprzEVgsUBKXy2B93McsREmvP320/e9ZS27oQx7wgAyqi1N8rVNy3Qe3cK3ZaNDI5zSkg6spkhy+20eRFaWGYoTHR/7V2MabYDKh1BWiyrvBfUnuMdKHwHAoXMmsm36WBkeNIUCQrgpGtolFJEmlO4/KsJe6xCIftwLE2R3jBKN301Rcli6FfPrv6q5DPpZxXBjAK4J5fuQwTMEe5VjdGZ97UNcpLAB9507aK+hn3gR59AYiWJUEkziv81Oq3SbWBKX4wKyd+Q0SR++92FBqRmQnKlHsIW70e7zzXV7HYlqI/TuejiNTbe+t+hjH8N6saiBe2zEW9vE2FuxNMlR09fs8ZhgCAYUGftlLiCnwHOl4t/SrkFInEw7vfXQZvP3c8B3EAumUwYA3LWHCnRGu8NE5bOFS+SlX5z5YUbpDN717TWJbOL6YJZPk+8d4r++V3fXM3wMBouA4WyD2tQmcnw6HwCOP5325jorM8vOgKnPz22zBt217ct6i/G9Mkc1ZHrV8QqRuLS4MNP5JW1osBjYgAa41wor/R3rMisVs8/LY23Pk7Z4JZgxuoJ/mJbE1ljMWxTCEbx4QUOL9MWWV6M3i+XnJLqy0j2jfcN3dsI9vdy9Y6FHxgOsbKbm4ScQjmdnc5xaXtPZEpI=
