language: r
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libhunspell-dev
      # - hunspell-en-au

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
