language: r
cache: packages
warnings_are_errors: true

before_install:
  - tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize

addons:
  apt:
    packages:
      - libhunspell-dev
      # - hunspell-en-au

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - Rscript -e 'cat(readLines("./tests/testthat/SchoolFunding/SchoolFunding.log"), sep = "\n")'
