language: r
cache: packages
warnings_are_errors: true
before_install:
- tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator
  needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
addons:
  apt:
    packages:
    - libhunspell-dev
r_packages:
- covr
- drat
- devtools
- roxygen2
- hunspell
after_success:
- Rscript -e 'devtools::test()'
- Rscript -e 'covr::codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
env:
  global:
  - secure: HuXY7LZ9bpqFmhVZ8TgWddMz0akvdBOj2vKkC0qbxBC7kiowTYJb94aJBjAmskC+Jjy7d/h5LiP7Qbeec74d6wzptIBPVXY1FO1luFlgdnSPB75n0bInMZ6b+mFdB+8Y5iwQqpEFHZoNRur8JOyt+uEdwwZXcYacFPTJwMtlM9WiaPBsdmglyEtdcCGJQ9PERFtVsXEMh06Xt1XDcvlWHuwJVLToXA/G9ml/tiwrj8dJDKTrmH8abYAWKhy42S1PEAeh4GKwYrEgriQPRKlPIt4XDvSB6hFv30D4Q+CkD1vIp+Es5DZIiygCu7KmDhuKv0QNDvu6O6akji3eDeCPj5hA3jYp/SkeD34aRNmq1N9gKqM+qCi0UJna2cGmjjUkEPqySzHt0rY3mFS7joo7dxUdbgTbVt3/Ep7W3ErbBEpZ+4G41xqPoKYnlIWzknmbBH8dFSbdthXGTFR7Es0V+8SObqXnK5gKI5wdueFeVLfV1ky6D/Lw5Xwx7cDP2I24iIYf263fS9B9CDnjB3dMQXfNARbqTOQZux9KbTqko7JGAuGFJObO0x0mctQUBeGl8H2po2fGhpjXdL7A9azvgTK5MmD/za+Cji8ScN4TXaN4mGgjNO/qBhxXyWwZs2iz8vMVvO+eVtt7hxsliipM3Q8+x0VlIrP/Ff1ZCAiH1Rs=
