language: r
cache: packages
warnings_are_errors: true
before_install:
- tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator
  needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
addons:
  apt:
    packages:
    - libhunspell-dev
r_packages:
- covr
- drat
- devtools
- roxygen2

after_success:
- Rscript -e 'devtools::test()'
- Rscript -e 'covr::codecov()'
