language: r
cache: packages
warnings_are_errors: true

before_install:
  - tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
  - wget "https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz"
  - tar xzf biber-linux_x86_64.tar.gz
  - tlmgr update biber

addons:
  apt:
    packages:
      - libhunspell-dev
      # - hunspell-en-au

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
